Lidar_front_end:
   lidar_type: 1   # 1 for Livox-avia, 3 for Ouster-OS1-64
   N_SCANS: 6
   using_raw_point: 1
   point_step: 1
   
r3live_common:
   if_dump_log: 0                   # If recording ESIKF update log. [default = 0]
   record_offline_map: 1            # If recording offline map. [default = 1]
   pub_pt_minimum_views: 3          # Publish points which have been render up to "pub_pt_minimum_views" time. [default = 3]
   minimum_pts_size: 0.01           # The minimum distance for every two points in Global map (unit in meter). [default = 0.01] 
   image_downsample_ratio: 1        # The downsample ratio of the input image. [default = 1]
   estimate_i2c_extrinsic: 1        # If enable estimate the extrinsic between camera and IMU. [default = 1] 
   estimate_intrinsic: 1            # If enable estimate the online intrinsic calibration of the camera lens. [default = 1] 
   maximum_vio_tracked_pts: 600     # The maximum points for tracking. [default = 600]
   append_global_map_point_step: 4  # The point step of append point to global map. [default = 4]

r3live_vio:
   image_width: 1280
   image_height: 720
   camera_intrinsic:
      [636.5245361328125, 0.0, 635.6729736328125,
      0.0,  634.7903442382812, 366.147705078125,
      0.0, 0.0, 1.0 ]


   camera_dist_coeffs: [-0.05449240654706955, 0.06359218806028366, 0.00016181448881980032, -0.0009868403431028128, -0.02028072439134121]  #k1, k2, p1, p2, k3
   
   camera_ext_R:
       [-0.02716453, -0.00297104,  0.99962612,
       -0.99951241,  0.01546283, -0.02711553,
       -0.01537646, -0.99987606, -0.00338962]
   camera_ext_t: [-0.01213753,-0.14412007,-0.01173265]        
   
r3live_lio:        
   lio_update_point_step: 4   # Point step used for LIO update.  
   max_iteration: 2           # Maximum times of LIO esikf.
   lidar_time_delay: 0        # The time-offset between LiDAR and IMU, provided by user. 
   filter_size_corner: 0.30   
   filter_size_surf: 0.30
   filter_size_surf_z: 0.30
   filter_size_map: 0.30
